### PR TITLE
Replace NSTimer with CADisplayLink and segue with dismissViewController

### PR DESCRIPTION
**Pull request by bgayman**
It is not recommended to use NSTimer for animations and other UI updates. Use CADisplayLink instead. Also to reverse view controller presentation you should use an unwind segue or dismissViewController not a forward segue as it will instantiate a new view controller and repeated initialization of view controllers can lead to memory warning/termination or suboptimal performance.

### CODE REVIEW

**Comment by DeveloperACE** [comment]
do you have any ideas as to how i could layout the UI? (see latest commit...)

**Comment by MoralCode** [comment]
@bgayman is there any way to set the CADisplayLink to run at specific intervals?

**Comment by bgayman** [comment]
Why would that be useful?

**Comment by MoralCode** [comment]
@bgayman i have a feature in the code (stressTestMode) that rapidly cycles through every time to test the clock and time display/calculation functionality...

**Comment by bgayman** [comment]
No, you can't set the interval. The interval is set by the system. You can use a timestamp to ignore calls, otherwise it will be called before each rendering pass, this ensure that you are getting optimal performance and that you will not drop frames. If you are just doing it for testing purposes it would be better to just log to console or if you feel it is necessary you can write a different function that advances time more rapidly rather than just reading it from NSDate. 

I don't know what you mean by "do you have any ideas as to how i could layout the UI? (see latest commit….)" You want the minute hand to sweep rather than tick?

**Comment by MoralCode** [comment]
okay.

i was referring to the conversion screen when i was talking about the UI, although a sweeping second hand may be a great optional feature!

do you have any idea how i can allow users to more rapidly increment/decrement the minutes and seconds on the conversion screen?

**Comment by MoralCode** [comment]
@bgayman i just looked at the timer using the code in this pull request, and have concluded that the occasional time skip (issue #3) is not due to the inaccuracy of the NSTimer (now CADisplayLink) but to the fact that there are 864 milliseconds in one metric second, as opposed to 1000 in "normal time"...

If you do find a fix for this, however, I would love to know what it is...

**Pull request merged**
