### PR TITLE
Add continuous sweeping of second hand and change interval meaning for stress test mode

### PR DESCRIPTION
**Pull request by bgayman**
This is how I would handle those things.

### CODE REVIEW

**Comment by MoralCode** [comment]
i have since removed stress-test mode... (commit 3e12f8b12e25076dbc624b2fe3febb0be82a003b)

**Comment by MoralCode** [comment]
how would the continuous sweep of the second hand handle the occasional time jump form issue #3?

**Comment by bgayman** [comment]
You should build from my branch and turn stressTest off and continuous on. I think you'll see it's not an issue.

**Comment by MoralCode** [comment]
@bgayman sorry for the lack of a response, this is my first real github project and i've been having some technical difficulties...

I have a question about your implementation of a continuously-sweeping second hand. Is there any particular reason the `seconds` and `convertedSeconds` variables are separate from the `actualTime` and `metricTime` arrays?

**Comment by MoralCode** [comment]
phew! now i just need to make it work with the `actualTime` and `metricTime` arrays...

**Pull request closed without merging**
